### ISSUE TITLE
tin depend .. error

### ISSUE THREAD

**Issue by abu-irrational** [ambaker1/Tin#30]
This looks like a circular dependency:  

% package require tin
1.0
% tin depend unit
can't find package unit , attempting to install ...
searching in the Tin for unit  ...
installing unit 0.1.3 from https://github.com/ambaker1/unit v0.1.3 ...
error in running installer file
can't find package tin 0.7

**Comment by ambaker1** [comment]
Resolved. Try this:
package require tin
tin upgrade tin
tin forget tin
package require tin
tin depend unit

**Comment by ambaker1** [comment]
also, as a side note - I noticed that you are working on some tcloo stuff - I'd check out vutil. I built a superclass for garbage collection and a type system framework.
